export const EVENT_SHEET_MAP: Record<string, string> = {
    "MISSION:POSSIBLE?": "CROWDFUNDING",
    "WOLF OF DALAL STREET": "WOLF_DALAL",
    "HOW TO TRAIN YOUR DELIVERY TEAM": "DELIVERY_TEAM",
    "MISIRLOU : A KNIVES OUT MYSTERY": "KNIVES_OUT",
    "ONE RED PAPERCLIP": "RED_PAPERCLIP",
    "WHAT DA FUKREY": "WING_TRADE",
    "BEDROCK": "BEDROCK",
    "DEHACK": "DEHACK"
};
